apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: f4i80nyxh-python 
  janus-idp.io/tekton: f4i80nyxh-python
  backstage.io/kubernetes-id: f4i80nyxh-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: f4i80nyxh-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml