apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: f4i80nyxh-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:19112fa28cc7f77341edd7142affb1f9e21ec03a@sha256:de6434892e0b47dee14889af6c73a193927cb0c4a0b74667f0cfa94e0e5e3a11
          name: container-image
